### ISSUE TITLE
plssem_gof() in lplssem, compiled by Stata 17.0 - doesn't work in Stata16

### ISSUE THREAD

**Issue by omit1974** [sergioventurini/plssem#1]
I use STATA 16.1. Below are the command and error message.

. plssem  ///
>         (IUa > iu1 iu2) /*(OUa > ou1 ou2 ou3)*/ (SIa > si1 si2 si3 si4) (EEa > ee1 ee2 ee3) ///
>         (PEa > pe1 pe2 pe3) (HMa > hm1 hm2 hm3 hm4)     (TMIa > tmi1 tmi2 tmi3 /*tmi4*/) ///
>         (TRa > tr1 tr2 tr3 tr4) (TAa > ta1 ta2 ta3 ta4 tmi4) /// (PRa > /*pr1*/ pr2 pr3)        ///
>         , structural (  ///
>         IUa PEa EEa SIa  TMIa HMa TAa TRa  ,    ///
>         ) /// group( POS, method(permutation) reps(1000) groupseed(19760303) plot alpha(0.1))   /// 
>         digits(3) maxiter(1000) /*boot(100)*/ nomeastable nodiscrimtable //   
(plssem_gof() in lplssem, compiled by Stata 17.0, is too new to be run by this version of Stata and so was ignored)
                 <istmt>:  3499  plssem_gof() not found

**Comment by sergioventurini** [comment]
I recompiled the library using Stata 16.1. Now you should be able to use all the functions.

**Comment by omit1974** [comment]
Excellent, it works again. Thank you so much for the prompt fix!
