### ISSUE TITLE
The PLSSEM cannot be ran after upgrading

### ISSUE THREAD

**Issue by PatricksonFang** [sergioventurini/plssem#2]
The error is:  sd():  3203  <tmp>[187,11] found where colvector required
                 <istmt>:     -  function returned error

**Comment by sergioventurini** [comment]
Hi, you should provide a full example (code + data) to allow us reproduce the error. Thanks.

**Comment by PatricksonFang** [comment]
I think the problem may be caused in version 18. The following is the code (No matter what data I use, the problem occurs, and I have reproduced this issue on different computers):
sysuse workout2, clear
plssem (Attractive > face sexy) (Appearance > body appear attract) (Muscle > muscle strength endur) (Weight > lweight calories cweight), structural(Appearance Attractive, Muscle Appearance, Weight Appearance)
error：sd():  3203  <tmp>[187,11] found where colvector required
                 <istmt>:     -  function returned error
set trace on and find the error appears on the line below:
  - mata: st_numscalar("`zerovar'", any(selectindex( sd(st_data(., "`allindicators'", "`touse'")) :== 0)))
  = mata: st_numscalar("__000004", any(selectindex( sd(st_data(., "face sexy body appear attract muscle strength endur l
> weight calories cweight", "__000002")) :== 0)))
                    sd():  3203  <tmp>[187,11] found where colvector required
                 <istmt>:     -  function returned error
  ---------------------------------------------------------------------------------------------- end plssem.Estimate ---
  }
--------------------------------------------------------------------------------------------------------- end plssem ---
r(3203);

**Comment by sergioventurini** [comment]
The code works fine for me. I use version 18. Which version are you using?

Btw, the core part of the sd() function is the following Mata computation:

mata: diagonal(sqrt(variance(X)))'

You may try it interactively in a Stata session and check if it works.

Let me know!

**Comment by PatricksonFang** [comment]
Yes, I also use version 18, the 22 May update.
I try the code and feasible:
sysuse auto
putmata X= ( price mpg trunk length weight displacement ) ,replace
(1 matrix posted)

. mata: diagonal(sqrt(variance(X)))'
                 1             2             3             4             5             6
    +-------------------------------------------------------------------------------------+
  1 |  2949.495885    5.78550321   4.277404189    22.2663399   777.1935671   91.83721896  |
    +-------------------------------------------------------------------------------------+

**Comment by sergioventurini** [comment]
I see.

So you mean that if you instead try

sysuse auto
putmata X = (price mpg trunk length weight displacement ), replace
mata: sd(X)

you get the error?

**Comment by PatricksonFang** [comment]
No, I can run the code correct
sysuse auto
putmata X = (price mpg trunk length weight displacement ), replace
mata: sd(X)

I also try stata17. The same error for PLSSEM:
  sd():  3203  <tmp>[187,11] found where colvector required
                 <istmt>:     -  function returned error

**Comment by sergioventurini** [comment]
That's pretty strange. To reproduce the error, and solve it, I need the data and the code you are using. You can anonymize the data if you want.

**Comment by sergioventurini** [comment]
I just uploaded a new version of the library that I compiled using Stata 17. Can you try it and tell me if it works now?

**Comment by PatricksonFang** [comment]
Thank you very much. I re-downloaded the newly compiled document, and now there are no issues. I believe the problem is that the compilation based on StataNow is now restricted to running on Stata 18.5. Thank you again for creating such an excellent ado file.

**Comment by sergioventurini** [comment]
I'm happy to know it is useful to someone!

**Comment by sergioventurini** [comment]
I'm happy to know it is useful to someone!
