### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by Jant2024** [sergioventurini/plssem#3]
Hello, I am trying to install plssem. When I copy the text for installing the package, I receive the error code:

Checking package dependencies
installing plssem package dependencies:

. net install nwcommands-ado.pkg, from(http://www.nwcommands.org)
http://www.nwcommands.org/ either
  1)  is not a valid URL, or
  2)  could not be contacted, or
  3)  is not a Stata download site (has no stata.toc file).

current site is still https://raw.githubusercontent.com/sergioventurini/plssem/master/
r(679);

end of do-file
r(679);

Could you please advise? 
Many thanks

**Comment by sergioventurini** [comment]
Unfortunately the issue is due to a dependency on another package, nwcommands, whose URL doesn't seem to work anymore. I've updated the installation removing the dependency and printing a message when it is needed. Let me know if now you can install our package correctly.

**Comment by Jant2024** [comment]
Hi Sergio,

Thanks for this. Yes it is working fine now!
