### ISSUE TITLE
Binary LV error

### ISSUE THREAD

**Issue by Jant2024** [sergioventurini/plssem#4]
Hi, I am trying to use the binary(LV) option in plssem but running into issues. When running the model without the binary option, it runs fine with no error, but as soon as I add the binary(LV) option it outputs the following error: 

warning: the use of binary latent variables goes beyond the original scopes of PLS-SEM. 
         They are provided here only for exploratory purposes.
           plssem_base():  3301  subscript invalid
                 <istmt>:     -  function returned error
Mata run-time error
r(3301);

This only seems to occur when the model is more complex. With only a few LVs the function runs with the binary option:
plssem (A < a)(B < b)(C < c1 c2), structural(A B, B C)binary(A). ---> works fine

plssem (A < a)(B < b)(C < c1 c2)(D < d1 d2 d3)(E < e1), structural(A B D, B C E) binary(A) ---> produces above error.

Could you please advise?
Many thanks

**Comment by sergioventurini** [comment]
Hi, to be able to reproduce this issue I need a full example (i.e. code and data). If you can't share the full data set, either you anonymize it or you can send me only a portion.

**Comment by Jant2024** [comment]
[plssem_sample_data.xlsx](https://github.com/user-attachments/files/16727293/plssem_sample_data.xlsx)

Hi Sergio,
Many thanks for your reply. I have attached an anonymised sample of data. The two pieces of code for model configurations are given below:

working model:
plssem (A < a)(B < b)(C < c1 c2), structural(A B, B C) binary(A)

model with error:
plssem (A < a)(B < b)(C < c1 c2)(D < d1 d2 d3)(E < e), structural(A B D, B C E) binary(A)

**Comment by sergioventurini** [comment]
I think I've found the bug. Please, verify that now it works correctly and send me your feedbacks.

**Comment by Jant2024** [comment]
Hi Sergio,

I reinstalled the package and ran the same code as above but still received the same error:

warning: the use of binary latent variables goes beyond the original scopes of PLS-SEM. 
         They are provided here only for exploratory purposes.
           plssem_base():  3301  subscript invalid
                 <istmt>:     -  function returned error
Mata run-time error
r(3301);

**Comment by sergioventurini** [comment]
dear Jant2024,

i tried the code you sent with Stata 17 and both model work fine.

either you install the package from scratch or send me more details, otherwise i wouldn’t be able to support you.

best,
sergio

**Comment by Jant2024** [comment]
Hi Sergio,

I did completely uninstall plssem and then reinstalled using the updated install code from the README file:

github install sergioventurini/plssem.

I am running on STATA 18. Do you think perhaps there is an issue with updating to the corrected code?

Kind regards,
Josh

**Comment by sergioventurini** [comment]
i removed all the files manually from my computer and resintalled the package using

github install sergioventurini/plssem

then, i ran your code in Stata 18 and it worked fine. i don’t know why you are getting the error message.


sergio

**Comment by Jant2024** [comment]
Hi Sergio,

Many thanks. The uninstall did not delete all the files, so I’ve manually done so and it is working now! Thanks for your patience and assistance!

Kind regards,
Josh

**Comment by Jant2024** [comment]
Hi Sergio,

Does the predict function work with binary latent variables with formative indicators? I am not sure if I am using the incorrect syntax but when running the predict function for the above data and pls model, I get:

. predict
(fitted values and residuals computed only for reflective latent variables)
(option xb assumed; fitted values)

invalid syntax
r(198);

And for the following:

. predict xb residuals

varlist not allowed
r(101);

**Comment by sergioventurini** [comment]
i have to check it. please, give me at least 3 or 4 days.

sergio

**Comment by sergioventurini** [comment]
dear jant2024,

there was a bug in returning the results of predict when there are no reflective constructs. i updated the code on github. now it should be fine.

please, let me know if you find further issues.

best,
sergio

**Comment by Jant2024** [comment]
Hi Sergio,

I can now use the predict function but for the binary endogeneous LV the output is not between 0 and 1. Using the same sample dataset and model structure some estimates are negative or above 1:

plssem (A < a)(B < b)(C < c1 c2)(D < d1 d2 d3)(E < e), structural(A B D, B C E) binary(A)
predict

Many thanks,
Josh

**Comment by sergioventurini** [comment]
oh, you are right, because currently i’m not using logistic regression for producing the predicitions of the binary latent variables. i need to work on this. i will let you know when i’m done.

best,
sergio

**Comment by sergioventurini** [comment]
i updated the predict command to produce 0/1 values in output for the fitted values of binary constructs. please, check that this works fine and makes it sense.

nonetheless, remind that the ‘binary’ option IS NOT an official feature of PLS-SEM, but one we provide exclusively for exploratory purposes. in other terms, do not pretend that journals or other people trained in PLS-SEM accept these results. our suggestion is to use only for your personal reasons. moreover, do not report anywhere that these numbers are “correct” simply because our package reports them.

best,
sergio

**Comment by Jant2024** [comment]
Hi Sergio,

Many thanks for this, the predictions are now binary.

Can I ask you whether it is possible to train the PLS model with training data, and then test the predictions with a new test dataset for validation?

Kind regards,
Josh

**Comment by sergioventurini** [comment]
Hi, yes, you can define a new variable for distinguishing training and test data and use the former for estimation using the if qualifier, while when you use predict do not use anything. it should compute the predictions for all the data.

sergio

**Comment by sergioventurini** [comment]
sorry, i was wrong in the last mail: currently you can’t ask for predictions using a subset of the data because if you fit a model using plssem with the if qualifier, this will save the latent scores only for the selected data. therefore, it won’t be possibile to compute the predictions for a different portion of the dataset (prediction caluclation require the latent scores).

we included this as a new feature to include in a future release.

best,
sergio

**Comment by Jant2024** [comment]
Hi Sergio,

Okay, thank you for clarifying!

Many thanks,
Josh
