### ISSUE TITLE
nwcommands error while installation

### ISSUE THREAD

**Issue by ThoriqAlayubi12** [sergioventurini/plssem#5]
i was try your package especially in postestimation result, when i try install nwcommands with the following instruction `net install nwcommands-ado.pkg` to generate the output from `plssemplot, innermodel` but i face the error message as below:

file https://raw.githubusercontent.com/sergioventurini/plssem/master/nwcommands-ado.pkg not found
could not load nwcommands-ado.pkg from https://raw.githubusercontent.com/sergioventurini/plssem/master/

thank you

**Comment by sergioventurini** [comment]
Hi, to run `plssemplot, innermodel` you need to first install the nwcommands package. Please refer to [https://nwcommands.wordpress.com](https://nwcommands.wordpress.com).
